accounts/urls.py
from django.conf.urls import url,include
from . import views

app_name='accounts'

urlpatterns = [
    url(r'^signup/', views.signup, name='signup'),
    url(r'^login/', views.loginview, name='login'),
    url(r'^logout/', views.logoutview, name='logout'),
]

post/urls.py
from django.conf.urls import url,include
from . import views

app_name='post'

urlpatterns = [
    url(r'^create/', views.create, name='create'),
    url(r'^(?P<pk>[0-9]+)/upvote', views.upvote, name='upvote'),
    url(r'^(?P<pk>[0-9]+)/downvote', views.downvote, name='downvote'),
    url(r'^user/(?P<fk>[0-9]+)', views.userpost, name='userpost'),
]

redditclone/urls.py
from django.conf.urls import url,include
from django.contrib import admin
import accounts.views
from post import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^post/', include('post.urls')),
    url(r'^$', views.home, name="home"),
]

accounts/models.py
from django.db import models

# Create your models here.

post/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class Post(models.Model):
    title = models.CharField(max_length=200)
    url = models.TextField()
    pub_date = models.DateTimeField()
    author = models.ForeignKey(User)
    votes_total = models.IntegerField(default = 0)

    def pub_date_pretty(self):
        return self.pub_date.strftime('%e %b %Y')

account/views.py
from django.shortcuts import render
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login

# Create your views here.
def signup(request):
    if request.method == 'POST':
        if request.POST['password'] == request.POST['password_conf']:
            try:
                user= User.objects.get(username=request.POST['username'])
                return render(request, 'account/signup.html', {'error':'Username already taken!'})
            except User.DoesNotExist:

                user = User.objects.create_user(request.POST['username'],  password=request.POST['password'])
                login(request, user)
                return render(request, 'account/signup.html')
        else:
            return render(request, 'account/signup.html', {'error':'Password didn\'t match!'})
    else:
        return render(request, 'account/signup.html')

def loginview(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return render(request, 'account/login.html', {'error':'Login Successful!!'})
        # Redirect to a success page.
        else:
        # Return an 'invalid login' error message.
            return render(request, 'account/login.html', {'error':'Authentication Error!'})
    else:
            return render(request, 'account/login.html')

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout

# Create your views here.
def signup(request):
    if request.method == 'POST':
        if request.POST['password'] == request.POST['password_conf']:
            try:
                user= User.objects.get(username=request.POST['username'])
                return render(request, 'accounts/signup.html', {'error':'Username already taken!'})
            except User.DoesNotExist:

                user = User.objects.create_user(request.POST['username'],  password=request.POST['password'])
                login(request, user)
                return render(request, 'accounts/signup.html')
        else:
            return render(request, 'accounts/signup.html', {'error':'Password didn\'t match!'})
    else:
        return render(request, 'accounts/signup.html')

def loginview(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            if 'next' in request.POST and request.POST['next'] is not None:
                return redirect(request.POST['next'])
            return redirect('home')
        # Redirect to a success page.
        else:
        # Return an 'invalid login' error message.
            return render(request, 'accounts/login.html', {'error':'Authentication Error!'})
    else:
            return render(request, 'accounts/login.html')

def logoutview(request):
    if request.method == 'POST':
        logout(request)
        return redirect('home')

post/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.utils import timezone
from .models import Post
from django.contrib.auth.models import User


# Create your views here.
@login_required
def create(request):
    if request.method == 'POST':
        if request.POST['title'] and request.POST['url']:
            post=Post()
            post.title=request.POST['title']
            if request.POST['url'].startswith('http://') or request.POST['url'].startswith('https://'):
                post.url= request.POST['url']
            else:
                post.url= 'http://' + request.POST['url']
            post.pub_date = timezone.datetime.now()
            post.author = request.user
            post.save()
            return redirect('home')

        else:
            return render(request, 'post/create.html', {'error':'ERROR: You must include a title and a URL to create a Post!'})
    else:
        return render(request, 'post/create.html')

def home(request):

    post=Post.objects.order_by('-votes_total')

    return render(request, 'post/home.html', {'post':post})

def upvote(request, pk):
    if request.method == 'POST':
        post = Post.objects.get(pk=pk)
        post.votes_total += 1
        post.save()
    return redirect('home')

def downvote(request, pk):
    if request.method == 'POST':
        post = Post.objects.get(pk=pk)
        post.votes_total -= 1
        post.save()
    return redirect('home')

def userpost(request, fk):
    post=Post.objects.filter(author__id=fk).order_by('-votes_total')
    author = User.objects.get(pk=fk)
    return render(request, 'post/userpost.html', {'post':post, 'author':author})

accounts/templates/accounts/login.html
{% extends 'base.html' %}

{% block content %}


<h1>Login</h1>

{% if error %}
{{ error }}
</br>
</br>
{% endif %}


<form method="POST" action="{% url 'accounts:login' %}">
  {% csrf_token %}

  {% if request.GET.next %}
  <input type="hidden" name="next" value= {{request.GET.next}}/>
  {% endif %}

  Username:
</br>
  <input type="text" name="username"/>
  </br>
  Password:
</br>
  <input type="password" name="password"/>
  </br>
  </br>
  <input class="btn btn-dark" type="submit" value="Sign In"/>
</form>
{% endblock %}

accounts/templates/accounts/signup.html
{% extends 'base.html' %}

{% block content %}

<h1>Hello this is the signup page!!</h1>

{% if error %}
{{ error }}
</br>
</br>
{% endif %}


<form method="POST" action="{% url 'accounts:signup' %}">
  {% csrf_token %}

  Username: </br>
    <input type="text" name="username"/>
</br>
Password:
</br>
  <input type="password" name="password"/>
</br>
Confirm Password:
</br>
 <input type="password" name="password_conf"/>
</br>
</br>
  <input class="btn btn-dark" type="submit" value="Sign Up"/>
</form>
{% endblock %}

post/templates/post/create.html
{% extends 'base.html' %}

{% block content %}

<h1>New Post</h1>

{% if error %}
{{ error }}
</br>
</br>
{% endif %}


<form method="POST" action="{% url 'post:create' %}">
  {% csrf_token %}

  Title:
    </br>
  <input type="text" name="title"/>
  </br>
  URL:
  </br>
  <input type="text" name="url"/>
  </br>
  </br>
  <input class="btn btn-dark" type="submit" value="Post"/>
</form>
{% endblock %}

post/templates/post/home.html
{% extends 'base.html' %}

{% block content %}

<h1>This is the page to Nowhere!</h1>

<a class="btn btn-dark" href="{% url 'post:create' %}">New Post</a>

</br>
</br>

{% for post in post.all %}

<table>
  <tr>
    <td style="padding-right: 20px;"><a href="#" onClick="document.getElementById('upvote{{ post.id }}').submit()"><i class="fas fa-caret-up"></i></a></br>{{post.votes_total}}</br>
      <a href="#" onClick="document.getElementById('downvote{{ post.id }}').submit()"><i class="fas fa-caret-down"></i></a></td>
    <td><a href="{{ post.url }}">{{post.title}}</a></br>{{post.pub_date_pretty}} by {{post.author.username}}</td>
  </tr>
</table>
</br>

<form id="upvote{{ post.id }}" method="POST" action="{% url 'post:upvote' post.id%}">
  {% csrf_token %}
  <input type="hidden"></form>


  <form id="downvote{{ post.id }}" method="POST" action="{% url 'post:downvote' post.id%}">
 {% csrf_token %}
 <input type="hidden"></form>

{% endfor %}
{% endblock %}

post/templates/post/userpost.html
{% extends 'base.html' %}

{% block content %}

<h1>This is the posts of {{author.username}}!</h1>
</br>

{% for post in post.all %}

<table>
  <tr>
    <td style="padding-right: 20px;"><a href="#" onClick="document.getElementById('upvote{{ post.id }}').submit()"><i class="fas fa-caret-up"></i></a></br>{{post.votes_total}}</br>
      <a href="#" onClick="document.getElementById('downvote{{ post.id }}').submit()"><i class="fas fa-caret-down"></i></a></td>
    <td><a href="{{ post.url }}">{{post.title}}</a></br>{{post.pub_date_pretty}} by {{post.author.username}}</td>
  </tr>
</table>
</br>

<form id="upvote{{ post.id }}" method="POST" action="{% url 'post:upvote' post.id%}">
  {% csrf_token %}
  <input type="hidden"></form>


  <form id="downvote{{ post.id }}" method="POST" action="{% url 'post:downvote' post.id%}">
 {% csrf_token %}
 <input type="hidden"></form>

{% endfor %}
{% endblock %}

templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.4.1/css/all.css" integrity="sha384-5sAR7xN1Nv6T6+dT2mhtzEpVJvfS3NScPQTrOxhwjIuvcA67KV2R5Jz6kr4abQsz" crossorigin="anonymous">
    <title>Robim's Blog!</title>
  </head>
  <body>

    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#mynav">
      <span class="navbar-toggler-icon"></span>
    </button>
    <a class="navbar-brand" href="{% url 'home' %}">Reddit Clone</a>
      <div class="collapse navbar-collapse" id="mynav">
        <ul class="nav navbar-nav justified-content-right">
          {% if user.is_authenticated %}
          <li class="nav-item active">
            <a class="nav-link" href="#" onClick="document.getElementById('logout').submit()">Logout </a>
          </li>
          <form id="logout" method="POST" action="{% url 'accounts:logout' %}">
            {% csrf_token %}
            <input type="hidden">
          </form>
          {% else %}
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'accounts:signup' %}">Sign Up</a>
          </li>
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'accounts:login' %}">Login</a>
          </li>
          {% endif %}



        </ul>
      </div>
    </nav>


    <div class="container-fluid">
      {% block content %}
      {% endblock %}

  </div>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
  </body>
</html>